// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs9U0EGI0SlY04CqxsnWWi21jTiyR8wQk',
    appId: '1:1024268444186:web:cc185c91b762fb7375e7a3',
    messagingSenderId: '1024268444186',
    projectId: 'electiva-2026',
    authDomain: 'electiva-2026.firebaseapp.com',
    storageBucket: 'electiva-2026.firebasestorage.app',
    measurementId: 'G-GM35LLV1J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd7s1bhL8mPboaVSEG_eEZWxaW4sSr9lc',
    appId: '1:1024268444186:android:3d68e0803cf4c78a75e7a3',
    messagingSenderId: '1024268444186',
    projectId: 'electiva-2026',
    storageBucket: 'electiva-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7ZNRQ_ySNvMgF3jHWKsSamMapAXH4cv8',
    appId: '1:1024268444186:ios:ee8fd19fd032f78475e7a3',
    messagingSenderId: '1024268444186',
    projectId: 'electiva-2026',
    storageBucket: 'electiva-2026.firebasestorage.app',
    iosBundleId: 'com.example.electiva2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7ZNRQ_ySNvMgF3jHWKsSamMapAXH4cv8',
    appId: '1:1024268444186:ios:ee8fd19fd032f78475e7a3',
    messagingSenderId: '1024268444186',
    projectId: 'electiva-2026',
    storageBucket: 'electiva-2026.firebasestorage.app',
    iosBundleId: 'com.example.electiva2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs9U0EGI0SlY04CqxsnWWi21jTiyR8wQk',
    appId: '1:1024268444186:web:94029e25e936173c75e7a3',
    messagingSenderId: '1024268444186',
    projectId: 'electiva-2026',
    authDomain: 'electiva-2026.firebaseapp.com',
    storageBucket: 'electiva-2026.firebasestorage.app',
    measurementId: 'G-J8N667KCYM',
  );
}
